# Generated by Django 4.1 on 2022-09-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('anons', models.CharField(max_length=250, verbose_name='Тема')),
                ('full_text', models.TextField(verbose_name='Отзыв')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
            ],
        ),
    ]
